dataset: ptb
experiment_type: single
fidelity_list:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 9
- 12
- 15
- 19
- 24
- 30
- 38
- 49
fidelity_single: 5
max_hpo_time: 900
out_dir: pnlp_nohyper_0
predictor: rf
search_space: nlp
seed: 72
test_size: 200
train_size_list:
- 5
- 8
- 14
- 24
- 42
- 71
- 121
- 205
- 347
- 589
- 1000
train_size_single: 100
uniform_random: 1
