seed: 0
optimizer: rsws
search_space: nasbenchasr
dataset: timit
out_dir: test

experiment_type: single
predictor: oneshot
test_size: 200
train_size_list: [8, 12]
train_size_single: 2
fidelity_list: [5]
fidelity_single: 5

search:
  seed: 0  # 1235
  checkpoint_freq: 1000
  epochs: 40
  fidelity: -1

  # RE
  sample_size: 10
  population_size: 30
  
  # LS
  num_init: 10
    
  # BP
  predictor_type: oneshot
  debug_predictor: False
  
  # additional params
  batch_size: 2 # 64
  learning_rate: 0.0001
  learning_rate_min: 0.0
  momentum: 0.9
  weight_decay: 0.0003
  warm_start_epochs: 0
  grad_clip: 5
  train_portion: 0.9

  unrolled: False
  arch_learning_rate: 0.0003
  arch_weight_decay: 0.001
  output_weights: True
  

evaluation:
  checkpoint_freq: 5000
  batch_size: 96
  learning_rate: 0.025
  learning_rate_min: 0.00
  momentum: 0.9
  weight_decay: 0.0003
  epochs: 600
  warm_start_epochs: 0
  grad_clip: 5
  train_portion: 1.
  data_size: 50000

  cutout: True
  cutout_length: 16
  cutout_prob: 1.0
  drop_path_prob: 0.2
  auxiliary_weight: 0.4

