dataset: cifar10
experiment_type: single
fidelity_list:
- 1
- 2
- 3
- 4
- 5
- 7
- 10
- 14
- 18
- 25
- 33
- 44
- 60
- 80
- 106
fidelity_single: 5
max_hpo_time: 900
out_dir: p101_nohyper_0
predictor: gp
search_space: nasbench101
seed: 42
test_size: 200
train_size_list:
- 5
- 8
- 14
- 24
- 42
- 71
- 121
- 205
- 347
- 589
- 1000
train_size_single: 100
uniform_random: 1
