dataset: timit
experiment_type: single
fidelity_list:
- 1
- 2
- 2
- 3
- 4
- 5
- 6
- 8
- 10
- 13
- 16
- 20
- 25
- 32
- 40
fidelity_single: 5
max_hpo_time: 900
out_dir: pasr_nohyper_0
predictor: mlp
search_space: asr
seed: 13
test_size: 200
train_size_list:
- 5
- 8
- 14
- 24
- 42
- 71
- 121
- 205
- 347
- 589
- 1000
train_size_single: 100
uniform_random: 1
