dataset: classScene
experiment_type: single
fidelity_list:
- 1
- 2
- 3
- 5
- 7
- 9
- 13
- 19
- 26
- 37
- 52
- 73
- 102
- 142
- 199
fidelity_single: 5
max_hpo_time: 900
out_dir: ptransmacro_nohyper_0
predictor: rf
search_space: transbench101_macro
seed: 17
test_size: 200
train_size_list:
- 5
- 8
- 14
- 24
- 42
- 71
- 121
- 205
- 347
- 589
- 1000
train_size_single: 100
uniform_random: 1
